# Generated by Django 5.0 on 2024-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('UNAVAILABLE', 'Unavailable'), ('UPCOMMING', 'Upcomming')], default='VAT', max_length=20),
        ),
    ]
