# Generated by Django 5.0 on 2024-06-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('SHIPPING', 'Shipping'), ('VAT', 'Vat')], default='VAT', max_length=20),
        ),
    ]
