# Generated by Django 5.0 on 2024-06-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FeMale'), ('OTHERS', 'Others')], default='MALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FeMale'), ('OTHERS', 'Others')], default='MALE', max_length=20),
        ),
    ]
